### ISSUE TITLE
CMake with unit test fails

### ISSUE THREAD

**Issue by kletze** [improvess/raspberry-as-gige-camera#11]
## Error description:
when building with unit tests cmake fails loading googletest:
Running cmake with the option `DBUILD_TESTS=ON ` fails because the branchname changed from master to main.
Error Message:
```
DBUILD_TESTS=ON ..
-- Build type is RelWithDebInfo
-- Building for architecture: aarch64
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stefan/Camera/raspberry-as-gige-camera/code/libs/googletest/download
Scanning dependencies of target googletest
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'src'...
fatal: invalid reference: master
CMake Error at download/googletest-prefix/tmp/googletest-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'
```

## fix:
change the GIT_TAG in [code/libs/googletest/CMakeLists.txt.in](https://github.com/improvess/raspberry-as-gige-camera/blob/main/code/libs/googletest/CMakeLists.txt.in) from ```master``` to ```main```:
```
cmake_minimum_required(VERSION 2.8.2)
project(googletest-download NONE)

include(ExternalProject)
ExternalProject_Add(googletest
  GIT_REPOSITORY    https://github.com/google/googletest.git
  GIT_TAG           main
  SOURCE_DIR        "../src"
  BINARY_DIR        "../build"
  CONFIGURE_COMMAND ""
  BUILD_COMMAND     ""
  INSTALL_COMMAND   ""
  TEST_COMMAND      ""
)
```

[Pull Request](https://github.com/kletze/raspberry-as-gige-camera/pull/1/commits/e9b28aa64ecf4fff4ccbe577bbbc4a378faa7ad4)

**Comment by doleron** [comment]
ops, it seems the PR was for your fork, can you be kindly to open it to the main repo? Thank you

**Comment by kletze** [comment]
Oh sorrey created a new pull request for the main repo.

**Comment by doleron** [comment]
FIx by https://github.com/improvess/raspberry-as-gige-camera/pull/12
